export const CREATE_CITIES = 'CREATE_CITIES';
export const CREATE_CITIES_SUCCESS = 'CREATE_CITIES_SUCCESS';
export const CREATE_CITIES_FAILURE = 'CREATE_CITIES_FAILURE';


export const READ_CITIES = 'READ_CITIES';
export const READ_CITIES_SUCCESS = 'READ_CITIES_SUCCESS';
export const READ_CITIES_FAILURE = 'READ_CITIES_FAILURE';

export const EDIT_CITIES = 'EDIT_CITIES';
export const EDIT_CITIES_SUCCESS = 'EDIT_CITIES_SUCCESS';
export const EDIT_CITIES_FAILURE = 'EDIT_CITIES_FAILURE';

export const UPDATE_CITIES = 'UPDATE_CITIES';
export const UPDATE_CITIES_SUCCESS = 'UPDATE_CITIES_SUCCESS';
export const UPDATE_CITIES_FAILURE = 'UPDATE_CITIES_FAILURE';

export const DELETE_CITIES = 'DELETE_CITIES';
export const DELETE_CITIES_SUCCESS = 'DELETE_CITIES_SUCCESS';
export const DELETE_CITIES_FAILURE = 'DELETE_CITIES_FAILURE';

export const FILTER_CITIES = 'FILTER_CITIES';
export const FILTER_CITIES_SUCCESS = 'FILTER_CITIES_SUCCESS';
export const FILTER_CITIES_FAILURE = 'FILTER_CITIES_FAILURE';

export const SEARCH_CITIES = 'SEARCH_CITIES';
export const SEARCH_CITIES_SUCCESS = 'SEARCH_CITIES_SUCCESS';
export const SEARCH_CITIES_FAILURE = 'SEARCH_CITIES_FAILURE';




export const CREATE_USERS = 'CREATE_USERS';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const CREATE_USERS_FAILURE = 'CREATE_USERS_FAILURE';


export const READ_USERS = 'READ_USERS';
export const READ_USERS_SUCCESS = 'READ_USERS_SUCCESS';
export const READ_USERS_FAILURE = 'READ_USERS_FAILURE';

export const EDIT_USERS = 'EDIT_USERS';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const EDIT_USERS_FAILURE = 'EDIT_USERS_FAILURE';

export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_FAILURE = 'UPDATE_USERS_FAILURE';

export const DELETE_USERS = 'DELETE_USERS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE';

export const FILTER_USERS = 'FILTER_USERS';
export const FILTER_USERS_SUCCESS = 'FILTER_USERS_SUCCESS';
export const FILTER_USERS_FAILURE = 'FILTER_USERS_FAILURE';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';




